version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    networks:
      - default

  db:
    image: postgres
    env_file:
      - .env.db
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - default